export const eventTypes = [
  "Birthday",
  "Wedding",
  "Anniversary",
  "Baby Shower",
  "Graduation Party",
  "Family Reunion",
  "Conference",
  "Seminar",
  "Workshop",
  "Product Launch",
  "Team Building",
  "Award Ceremony",
  "Networking Event",
  "Religious Ceremony",
  "Cultural Festival",
  "Engagement Party",
  "Retirement Party",
  "Surprise Party",
  "Other",
];